name: build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Build with Maven
        run: mvn -B -ntp verify
      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v6.0.0
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "**/target/*-reports/TEST-*.xml"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./microservice
          push: false
          tags: itatm/ezldap:${{ env.GITHUB_REF_NAME_SLUG }}
